// Generated by github.com/davyxu/tabtoy
// Version: 
// DO NOT EDIT!!
using System.Collections.Generic;

namespace table
{
	
	// Defined in table: Globals
	public enum ActorType
	{
		
		
		Leader = 0, // 唐僧
		
		
		Monkey = 1, // 孙悟空
		
		
		Pig = 2, // 猪八戒
		
		
		Hammer = 3, // 沙僧
	
	}
	
	

	// Defined in table: Configss
	
	public partial class Configss
	{
	
		public tabtoy.Logger TableLogger = new tabtoy.Logger();
	
		
		/// <summary> 
		/// Sample
		/// </summary>
		public List<SampleDefine> Sample = new List<SampleDefine>(); 
		
		/// <summary> 
		/// Sam
		/// </summary>
		public List<SamDefine> Sam = new List<SamDefine>(); 
	
	
		#region Index code
	 	Dictionary<long, SampleDefine> _SampleByID = new Dictionary<long, SampleDefine>();
        public SampleDefine GetSampleByID(long ID, SampleDefine def = default(SampleDefine))
        {
            SampleDefine ret;
            if ( _SampleByID.TryGetValue( ID, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(SampleDefine) )
			{
				TableLogger.ErrorLine("GetSampleByID failed, ID: {0}", ID);
			}

            return def;
        }
		Dictionary<string, SampleDefine> _SampleByName = new Dictionary<string, SampleDefine>();
        public SampleDefine GetSampleByName(string Name, SampleDefine def = default(SampleDefine))
        {
            SampleDefine ret;
            if ( _SampleByName.TryGetValue( Name, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(SampleDefine) )
			{
				TableLogger.ErrorLine("GetSampleByName failed, Name: {0}", Name);
			}

            return def;
        }
		Dictionary<long, SamDefine> _SamByID = new Dictionary<long, SamDefine>();
        public SamDefine GetSamByID(long ID, SamDefine def = default(SamDefine))
        {
            SamDefine ret;
            if ( _SamByID.TryGetValue( ID, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(SamDefine) )
			{
				TableLogger.ErrorLine("GetSamByID failed, ID: {0}", ID);
			}

            return def;
        }
		Dictionary<string, SamDefine> _SamByName = new Dictionary<string, SamDefine>();
        public SamDefine GetSamByName(string Name, SamDefine def = default(SamDefine))
        {
            SamDefine ret;
            if ( _SamByName.TryGetValue( Name, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(SamDefine) )
			{
				TableLogger.ErrorLine("GetSamByName failed, Name: {0}", Name);
			}

            return def;
        }
		
		public string GetBuildID(){
			return "532527105051e70040ce8455a0fd94d2";
		}
	
		#endregion
		#region Deserialize code
		
		static tabtoy.DeserializeHandler<Configss> _ConfigssDeserializeHandler;
		static tabtoy.DeserializeHandler<Configss> ConfigssDeserializeHandler
		{
			get
			{
				if (_ConfigssDeserializeHandler == null )
				{
					_ConfigssDeserializeHandler = new tabtoy.DeserializeHandler<Configss>(Deserialize);
				}

				return _ConfigssDeserializeHandler;
			}
		}
		public static void Deserialize( Configss ins, tabtoy.DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0xa0000:
                	{
						ins.Sample.Add( reader.ReadStruct<SampleDefine>(SampleDefineDeserializeHandler) );
                	}
                	break; 
                	case 0xa0001:
                	{
						ins.Sam.Add( reader.ReadStruct<SamDefine>(SamDefineDeserializeHandler) );
                	}
                	break; 
                }
             } 

			
			// Build Sample Index
			for( int i = 0;i< ins.Sample.Count;i++)
			{
				var element = ins.Sample[i];
				
				ins._SampleByID.Add(element.ID, element);
				
				ins._SampleByName.Add(element.Name, element);
				
			}
			
			// Build Sam Index
			for( int i = 0;i< ins.Sam.Count;i++)
			{
				var element = ins.Sam[i];
				
				ins._SamByID.Add(element.ID, element);
				
				ins._SamByName.Add(element.Name, element);
				
			}
			
		}
		static tabtoy.DeserializeHandler<Vec2> _Vec2DeserializeHandler;
		static tabtoy.DeserializeHandler<Vec2> Vec2DeserializeHandler
		{
			get
			{
				if (_Vec2DeserializeHandler == null )
				{
					_Vec2DeserializeHandler = new tabtoy.DeserializeHandler<Vec2>(Deserialize);
				}

				return _Vec2DeserializeHandler;
			}
		}
		public static void Deserialize( Vec2 ins, tabtoy.DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0x10000:
                	{
						ins.X = reader.ReadInt32();
                	}
                	break; 
                	case 0x10001:
                	{
						ins.Y = reader.ReadInt32();
                	}
                	break; 
                }
             } 

			
		}
		static tabtoy.DeserializeHandler<Prop> _PropDeserializeHandler;
		static tabtoy.DeserializeHandler<Prop> PropDeserializeHandler
		{
			get
			{
				if (_PropDeserializeHandler == null )
				{
					_PropDeserializeHandler = new tabtoy.DeserializeHandler<Prop>(Deserialize);
				}

				return _PropDeserializeHandler;
			}
		}
		public static void Deserialize( Prop ins, tabtoy.DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0x10000:
                	{
						ins.HP = reader.ReadInt32();
                	}
                	break; 
                	case 0x50001:
                	{
						ins.AttackRate = reader.ReadFloat();
                	}
                	break; 
                	case 0x80002:
                	{
						ins.ExType = reader.ReadEnum<ActorType>();
                	}
                	break; 
                }
             } 

			
		}
		static tabtoy.DeserializeHandler<AttackParam> _AttackParamDeserializeHandler;
		static tabtoy.DeserializeHandler<AttackParam> AttackParamDeserializeHandler
		{
			get
			{
				if (_AttackParamDeserializeHandler == null )
				{
					_AttackParamDeserializeHandler = new tabtoy.DeserializeHandler<AttackParam>(Deserialize);
				}

				return _AttackParamDeserializeHandler;
			}
		}
		public static void Deserialize( AttackParam ins, tabtoy.DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0x10000:
                	{
						ins.Value = reader.ReadInt32();
                	}
                	break; 
                }
             } 

			
		}
		static tabtoy.DeserializeHandler<SampleDefine> _SampleDefineDeserializeHandler;
		static tabtoy.DeserializeHandler<SampleDefine> SampleDefineDeserializeHandler
		{
			get
			{
				if (_SampleDefineDeserializeHandler == null )
				{
					_SampleDefineDeserializeHandler = new tabtoy.DeserializeHandler<SampleDefine>(Deserialize);
				}

				return _SampleDefineDeserializeHandler;
			}
		}
		public static void Deserialize( SampleDefine ins, tabtoy.DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0x20000:
                	{
						ins.ID = reader.ReadInt64();
                	}
                	break; 
                	case 0x60001:
                	{
						ins.Name = reader.ReadString();
                	}
                	break; 
                	case 0x60002:
                	{
						ins.EmptyName = reader.ReadString();
                	}
                	break; 
                	case 0x10003:
                	{
						ins.IconID = reader.ReadInt32();
                	}
                	break; 
                	case 0x50004:
                	{
						ins.NumericalRate = reader.ReadFloat();
                	}
                	break; 
                	case 0x10005:
                	{
						ins.ItemID = reader.ReadInt32();
                	}
                	break; 
                	case 0x10006:
                	{
						ins.BuffID.Add( reader.ReadInt32() );
                	}
                	break; 
                	case 0x90007:
                	{
						ins.Pos = reader.ReadStruct<Vec2>(Vec2DeserializeHandler);
                	}
                	break; 
                	case 0x80008:
                	{
						ins.Type = reader.ReadEnum<ActorType>();
                	}
                	break; 
                	case 0x10009:
                	{
						ins.SkillID.Add( reader.ReadInt32() );
                	}
                	break; 
                	case 0x9000a:
                	{
						ins.AttackParam = reader.ReadStruct<AttackParam>(AttackParamDeserializeHandler);
                	}
                	break; 
                	case 0x9000b:
                	{
						ins.SingleStruct = reader.ReadStruct<Prop>(PropDeserializeHandler);
                	}
                	break; 
                	case 0x9000c:
                	{
						ins.StrStruct.Add( reader.ReadStruct<Prop>(PropDeserializeHandler) );
                	}
                	break; 
                }
             } 

			
		}
		static tabtoy.DeserializeHandler<SamDefine> _SamDefineDeserializeHandler;
		static tabtoy.DeserializeHandler<SamDefine> SamDefineDeserializeHandler
		{
			get
			{
				if (_SamDefineDeserializeHandler == null )
				{
					_SamDefineDeserializeHandler = new tabtoy.DeserializeHandler<SamDefine>(Deserialize);
				}

				return _SamDefineDeserializeHandler;
			}
		}
		public static void Deserialize( SamDefine ins, tabtoy.DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0x20000:
                	{
						ins.ID = reader.ReadInt64();
                	}
                	break; 
                	case 0x60001:
                	{
						ins.Name = reader.ReadString();
                	}
                	break; 
                	case 0x60002:
                	{
						ins.EmptyName = reader.ReadString();
                	}
                	break; 
                	case 0x10003:
                	{
						ins.IconID = reader.ReadInt32();
                	}
                	break; 
                	case 0x50004:
                	{
						ins.NumericalRate = reader.ReadFloat();
                	}
                	break; 
                	case 0x10005:
                	{
						ins.ItemID = reader.ReadInt32();
                	}
                	break; 
                	case 0x10006:
                	{
						ins.BuffID.Add( reader.ReadInt32() );
                	}
                	break; 
                	case 0x90007:
                	{
						ins.Pos = reader.ReadStruct<Vec2>(Vec2DeserializeHandler);
                	}
                	break; 
                	case 0x80008:
                	{
						ins.Type = reader.ReadEnum<ActorType>();
                	}
                	break; 
                	case 0x10009:
                	{
						ins.SkillID.Add( reader.ReadInt32() );
                	}
                	break; 
                	case 0x9000a:
                	{
						ins.AttackParam = reader.ReadStruct<AttackParam>(AttackParamDeserializeHandler);
                	}
                	break; 
                	case 0x9000b:
                	{
						ins.SingleStruct = reader.ReadStruct<Prop>(PropDeserializeHandler);
                	}
                	break; 
                	case 0x9000c:
                	{
						ins.StrStruct.Add( reader.ReadStruct<Prop>(PropDeserializeHandler) );
                	}
                	break; 
                }
             } 

			
		}
		#endregion
		#region Clear Code
		public void Clear( )
		{			
				Sample.Clear(); 		
				Sam.Clear(); 
			
				_SampleByID.Clear(); 
				_SampleByName.Clear(); 
				_SamByID.Clear(); 
				_SamByName.Clear(); 
		}
		#endregion
	

	} 

	// Defined in table: Globals
	
	public partial class Vec2
	{
	
		
		
		public int X = 0; 
		
		
		public int Y = 0; 
	
	

	} 

	// Defined in table: Sample
	[System.Serializable]
	public partial class Prop
	{
	
		
		
		public int HP = 10; // 血量
		
		
		public float AttackRate = 0f; // 攻击速率
		
		
		public ActorType ExType = ActorType.Leader; // 额外类型
	
	

	} 

	// Defined in table: Sample
	[System.Serializable]
	public partial class AttackParam
	{
	
		
		
		public int Value = 0; // 攻击值
	
	

	} 

	// Defined in table: Sample
	[System.Serializable]
	public partial class SampleDefine
	{
	
		
		/// <summary> 
		/// 唯一ID
		/// </summary>
		public long ID = 0; 
		
		/// <summary> 
		/// 名称
		/// </summary>
		public string Name = ""; 
		
		
		public string EmptyName = ""; 
		
		/// <summary> 
		/// 图标ID
		/// </summary>
		public int IconID = 0; 
		
		/// <summary> 
		/// 攻击率
		/// </summary>
		public float NumericalRate = 0f; 
		
		/// <summary> 
		/// 物品id
		/// </summary>
		public int ItemID = 100; 
		
		/// <summary> 
		/// BuffID
		/// </summary>
		public List<int> BuffID = new List<int>(); 
		
		/// <summary> 
		/// 位置
		/// </summary>
		public Vec2 Pos = new Vec2(); 
		
		/// <summary> 
		/// 类型
		/// </summary>
		public ActorType Type = ActorType.Leader; 
		
		/// <summary> 
		/// 技能ID列表
		/// </summary>
		public List<int> SkillID = new List<int>(); 
		
		/// <summary> 
		/// 攻击参数
		/// </summary>
		public AttackParam AttackParam = new AttackParam(); 
		
		/// <summary> 
		/// 单结构解析
		/// </summary>
		public Prop SingleStruct = new Prop(); 
		
		/// <summary> 
		/// 字符串结构
		/// </summary>
		public List<Prop> StrStruct = new List<Prop>(); 
	
	

	} 

	// Defined in table: Sam
	[System.Serializable]
	public partial class SamDefine
	{
	
		
		/// <summary> 
		/// 唯一ID
		/// </summary>
		public long ID = 0; 
		
		/// <summary> 
		/// 名称
		/// </summary>
		public string Name = ""; 
		
		
		public string EmptyName = ""; 
		
		/// <summary> 
		/// 图标ID
		/// </summary>
		public int IconID = 0; 
		
		/// <summary> 
		/// 攻击率
		/// </summary>
		public float NumericalRate = 0f; 
		
		/// <summary> 
		/// 物品id
		/// </summary>
		public int ItemID = 100; 
		
		/// <summary> 
		/// BuffID
		/// </summary>
		public List<int> BuffID = new List<int>(); 
		
		/// <summary> 
		/// 位置
		/// </summary>
		public Vec2 Pos = new Vec2(); 
		
		/// <summary> 
		/// 类型
		/// </summary>
		public ActorType Type = ActorType.Leader; 
		
		/// <summary> 
		/// 技能ID列表
		/// </summary>
		public List<int> SkillID = new List<int>(); 
		
		/// <summary> 
		/// 攻击参数
		/// </summary>
		public AttackParam AttackParam = new AttackParam(); 
		
		/// <summary> 
		/// 单结构解析
		/// </summary>
		public Prop SingleStruct = new Prop(); 
		
		/// <summary> 
		/// 字符串结构
		/// </summary>
		public List<Prop> StrStruct = new List<Prop>(); 
	
	

	} 

}
