package export

import (
	"bytes"
	"text/template"
)

type CsharpGlobalTemplateParam struct {
	ClassName   string
	KeyName     string
	KeyType     string
	DataDefine  string
	Deserialize string
}

const csharpTemplateGlobal = `// Generated by code
// DO NOT EDIT!!
using System.Collections.Generic;

namespace Schema
{
	public partial class {{.ClassName}}:ISchema
	{
		private {{.ClassName}}Define _data;

		public {{.ClassName}}Define Data { get { return _data; } }
	
		#region Deserialize code
		public void Deserialize(Config.DataReader reader )
		{
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
				var bound = reader._reader.ReadInt32();
				{{.ClassName}}Define element = new {{.ClassName}}Define(new Config.DataReader(reader, reader._reader.BaseStream.Position + bound));
				_data = element;
				break;
            } 
		}
		#endregion
		#region Clear Code
		public void Clear( )
		{			
			_data = null;
		}
		#endregion
		public void Release()
		{
			
		}
	} 

	[System.Serializable]
	public partial class {{.ClassName}}Define
	{
		{{.DataDefine}}
		public {{.ClassName}}Define(Config.DataReader reader)
		{
            {{.Deserialize}}
    	}
	} 
}
`

func (c *CsharpGlobalTemplateParam) GenerateCsharpTemplate() string {
	var buf bytes.Buffer
	t := template.Must(template.New("deserialize").Parse(csharpTemplateGlobal))
	if err := t.Execute(&buf, c); err != nil {
		panic("template execution failed: " + err.Error())
	}
	return buf.String()
}
